import type { YrestStorage } from "../storage/types.js";
import type { YrestOptions } from "../config/loadOptions.js";
import type { OpenApiDoc } from "./types.js";
import { buildCollectionSchema } from "./inferSchema.js";
import { buildCrudPaths, buildRelationPaths, buildCustomRoutePaths } from "./buildPaths.js";

/**
 * Generates a complete OpenAPI 3.0 document from the current storage state.
 *
 * Schema fields are inferred from the first 10 items per collection.
 * If a `_schema` block is present in `db.yml`, its declarations take priority
 * over inference for the fields it mentions (other fields remain inferred/optional).
 *
 * @param storage - Live yRest storage instance.
 * @param options - Server options (host, port, base).
 * @param title   - Optional API title for the `info` block.
 */
export function generateOpenApi(
  storage: YrestStorage,
  options: Pick<YrestOptions, "host" | "port" | "base">,
  title = "yRest API"
): OpenApiDoc {
  const collections = Object.keys(storage.getData());
  const relations = storage.getRelations();
  const schemaBlock = storage.getSchema();
  const customRoutes = storage.getRoutes();
  const base = options.base ?? "";

  // ── Component schemas ───────────────────────────────────────────────────────
  const schemas: Record<string, import("./types.js").SchemaObject> = {};

  for (const collection of collections) {
    const items = storage.getCollection(collection) ?? [];
    const fieldDefs = schemaBlock[collection] ?? {};
    const schemaName = toSchemaName(collection);
    schemas[schemaName] = buildCollectionSchema(items, fieldDefs);
  }

  // ── Paths ───────────────────────────────────────────────────────────────────
  const paths: OpenApiDoc["paths"] = {};

  for (const collection of collections) {
    const schemaName = toSchemaName(collection);
    Object.assign(paths, buildCrudPaths(collection, base, schemaName));
  }

  Object.assign(paths, buildRelationPaths(relations, base));
  Object.assign(paths, buildCustomRoutePaths(customRoutes, base));

  // ── Document ────────────────────────────────────────────────────────────────
  return {
    openapi: "3.0.3",
    info: {
      title,
      version: "1.0.0",
      description: "Generated by yRest from db.yml",
    },
    servers: [
      {
        url: `http://${options.host}:${options.port}${base}`,
        description: "yRest mock server",
      },
    ],
    paths,
    components: { schemas },
  };
}

function toSchemaName(collection: string): string {
  const withoutS = collection.endsWith("s") ? collection.slice(0, -1) : collection;
  return withoutS.charAt(0).toUpperCase() + withoutS.slice(1);
}
